# Generated by Django 4.0 on 2021-12-27 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Racao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mome', models.CharField(max_length=255)),
                ('quantidade', models.IntegerField()),
                ('preco', models.FloatField()),
                ('Distribuidora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='racao', to='core.distribuidora')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='racao', to='core.categoria')),
            ],
        ),
    ]
