# Generated by Django 4.0 on 2021-12-27 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_racao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='racao',
            old_name='Distribuidora',
            new_name='distribuidora',
        ),
        migrations.AddField(
            model_name='racao',
            name='marcas',
            field=models.ManyToManyField(related_name='racao', to='core.Marca'),
        ),
    ]
